import {StyleSheet} from "react-native"
export default StyleSheet.create({
  root:{
    backgroundColor:'#fff',
    height:'100%'
  },
  top:{
    flexDirection:'row',
    padding:10,
    justifyContent:'space-around',
    alignItems:'center',
    borderStyle:'solid',
    borderBottomColor:'#e8e8e8',
    borderBottomWidth:1
  },
  box:{
    padding:10,
    borderStyle:'solid',
    borderBottomColor:'#e8e8e8',
    borderBottomWidth:1,
    flexDirection:'row',
    flexWrap:'wrap',
  },
  boxItem:{
    paddingTop:10,
    paddingBottom:10,
    width:'30%',
    textAlign:'center',
    borderRadius:20,
    margin:5,
    backgroundColor:'#f5f5f5',
    color:'#00b38a',
  },
  active:{
    backgroundColor:'#00b38a',
    color:'#fff',
  },
  itemBox:{
    padding:10,
    paddingBottom:15,
    paddingTop:15,
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center',
    borderStyle:'solid',
    borderBottomColor:'#e8e8e8',
    borderBottomWidth:1
  }
});